env:
  browser: true
  es2021: true
  node: true
extends:
  - standard
parser: '@typescript-eslint/parser'
ignorePatterns:
  - '**/*.js'
parserOptions:
  ecmaVersion: latest
  sourceType: module
plugins:
  - '@typescript-eslint'
rules: {}
